name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'app/package-lock.json'
    
    - name: Install dependencies
      run: cd app && npm ci
    
    - name: Run linting
      run: cd app && npm run lint || true
    
    - name: Run tests
      run: cd app && npm test
    
    - name: Build
      run: cd app && npm run build
